### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by benfletcher** [alexanmtz/material-sense#1]
Sorry if I missed, but did you intend this to have an OSS license? Very helpful repo. Thanks!

**Comment by benfletcher** [comment]
I'm not really sure what it's licensed under. I'd say `MIT` is always a good choice, but I'm not too familiar with all the options.

**Comment by alexanmtz** [comment]
Thanks @benfletcher, I think MIT fits well in this context. I added already, thanks 🙏
