### ISSUE TITLE
Warning: Failed prop type: Invalid prop `spacing` of value `24` supplied to `ForwardRef(Grid)`, expected one of [0,1,2,3,4,5,6,7,8,9,10].

### ISSUE THREAD

**Issue by amechax** [alexanmtz/material-sense#15]
Warning: Failed prop type: Invalid prop `spacing` of value `24` supplied to `ForwardRef(Grid)`, expected one of [0,1,2,3,4,5,6,7,8,9,10].
in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
in WithStyles(ForwardRef(Grid)) (at Topbar.js:131)
in div (created by ForwardRef(Toolbar))
in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
in WithStyles(ForwardRef(Toolbar)) (at Topbar.js:130)
in header (created by ForwardRef(Paper))
in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
in WithStyles(ForwardRef(Paper)) (created by ForwardRef(AppBar))
in ForwardRef(AppBar) (created by WithStyles(ForwardRef(AppBar)))
in WithStyles(ForwardRef(AppBar)) (at Topbar.js:129)
in Topbar (created by WithStyles(Topbar))
in WithStyles(Topbar) (created by Context.Consumer)
in withRouter(WithStyles(Topbar)) (at Main.js:123)
in Main (created by WithStyles(Main))
in WithStyles(Main) (created by Context.Consumer)
in withRouter(WithStyles(Main)) (created by Context.Consumer)
in Route (at routes.js:14)
in Switch (at routes.js:13)
in ScrollToTop (created by Context.Consumer)
in withRouter(ScrollToTop) (at routes.js:12)
in Router (created by HashRouter)
in HashRouter (at routes.js:11)
in Unknown (at App.js:32)
in ThemeProvider (at App.js:31)
in div (at App.js:30)
in App (at src/index.js:7)
Warning: Material-UI: the key `stepsContainer` provided to the classes property is not implemented in BaseDialog.
You can only override one of the following: container,bottomMargin.

**Comment by alexanmtz** [comment]
@amechax this will be covered at #5

**Comment by alexanmtz** [comment]
solved by #18
