### ISSUE TITLE
Topbar selection not marked after page change

### ISSUE THREAD

**Issue by darkmatus** [alexanmtz/material-sense#22]
Hello, every time I change the page on my syte and the content changes (actually under deployment) the blue line which mark the activ page won't change. 

Example: 
* starting with yarn start it opens with the main page and the main page is selected
* navigate to imprint the page switches, the content is loaded but main page is still marked as actual

This happens every time the content changes. A second click on the current page navigation item will mark them as active.

Does it have to do something with the error I got on the developer console?
`Material-UI: The key `stepsContainer` provided to the classes prop is not implemented in BaseDialog.
You can only override one of the following: container,bottomMargin.`

**Comment by alexanmtz** [comment]
Hello @darkmatus, 

Actually, the page is changing the address? You can see here a dashboard page: https://alexanmtz.github.io/material-sense/#/dashboard with the page marked, so the link is actually changing the URL? 

As in our live version, it is fully working, it seems something related to your environment.

**Comment by darkmatus** [comment]
Hi,  yes the URL is changed.
I also rollback the package versions to the repo versions because I did a package Update.

**Comment by alexanmtz** [comment]
So @darkmatus you need to debug https://github.com/alexanmtz/material-sense/blob/master/src/components/Topbar.js#L103

To check if is returning properly the index to mark the tab.

**Comment by darkmatus** [comment]
I will debug it after my vacation.

**Comment by darkmatus** [comment]
Thanks, I found it. the ``` <Topbar currentPath={currentPath} />``` was missing.

**Comment by alexanmtz** [comment]
that's great @darkmatus !
